name: npm publish
on:
  release:
    types: released
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-wasi
      - run: rustup target add wasm32-unknown-unknown
      - run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://registry.npmjs.org/
      - run: ./just build
      - run: npm publish
        working-directory: pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
